Torch distributed launch config settings: {'min_nodes': 2, 'max_nodes': 2, 'node_rank': 1, 'nproc_per_node': 1, 'rdzv_backend': 'static', 'rdvz_endpoint_url': 'torch-ddp-0-e7f79f1f-09db-42fa-bfbb-a465847e2851.argo.svc.cluster.local', 'rdvz_endpoint_port': 29200, 'run_id': '1', 'role': '', 'max_restarts': 3, 'monitor_interval': 30.0, 'redirects': '3', 'tee': '3', 'log_dir': None, 'log_line_prefix_template': None}
Torch distributed launch config settings: {'min_nodes': 2, 'max_nodes': 2, 'node_rank': 1, 'nproc_per_node': 1, 'rdzv_backend': 'static', 'rdvz_endpoint_url': 'torch-ddp-0-e7f79f1f-09db-42fa-bfbb-a465847e2851.argo.svc.cluster.local', 'rdvz_endpoint_port': 29200, 'run_id': '1', 'role': '', 'max_restarts': 3, 'monitor_interval': 30.0, 'redirects': '3', 'tee': '3', 'log_dir': None, 'log_line_prefix_template': None}
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.11/multiprocessing/spawn.py", line 122, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/multiprocessing/spawn.py", line 131, in _main
    prepare(preparation_data)
  File "/usr/local/lib/python3.11/multiprocessing/spawn.py", line 246, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/usr/local/lib/python3.11/multiprocessing/spawn.py", line 297, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen runpy>", line 291, in run_path
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "/argo/staging/script", line 57, in <module>
    torch_distributed_function(n_iter,n_seconds_sleep,duration)
  File "/src/bettmensch-ai/sdk/bettmensch_ai/torch_utils.py", line 120, in wrapper
    elastic_launch(
  File "/usr/local/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 254, in launch_agent
    result = agent.run()
             ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/distributed/elastic/metrics/api.py", line 123, in wrapper
    result = f(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/distributed/elastic/agent/server/api.py", line 733, in run
    result = self._invoke_run(role)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/distributed/elastic/agent/server/api.py", line 870, in _invoke_run
    self._initialize_workers(self._worker_group)
  File "/usr/local/lib/python3.11/site-packages/torch/distributed/elastic/metrics/api.py", line 123, in wrapper
    result = f(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/distributed/elastic/agent/server/api.py", line 708, in _initialize_workers
    worker_ids = self._start_workers(worker_group)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/distributed/elastic/metrics/api.py", line 123, in wrapper
    result = f(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/distributed/elastic/agent/server/local_elastic_agent.py", line 279, in _start_workers
    self._pcontext = start_processes(
                     ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/__init__.py", line 231, in start_processes
    context.start()
  File "/usr/local/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/api.py", line 454, in start
    self._start()
  File "/usr/local/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/api.py", line 627, in _start
    self._pc = mp.start_processes(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/multiprocessing/spawn.py", line 228, in start_processes
    process.start()
  File "/usr/local/lib/python3.11/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/local/lib/python3.11/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/local/lib/python3.11/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/multiprocessing/spawn.py", line 164, in get_preparation_data
    _check_not_importing_main()
  File "/usr/local/lib/python3.11/multiprocessing/spawn.py", line 140, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

        To fix this issue, refer to the "Safe importing of main module"
        section in https://docs.python.org/3/library/multiprocessing.html
        
E0709 21:30:16.481000 140636677933952 torch/distributed/elastic/multiprocessing/api.py:695] failed (exitcode: 1) local_rank: 0 (pid: 16) of fn: torch_ddp (start_method: spawn)
E0709 21:30:16.481000 140636677933952 torch/distributed/elastic/multiprocessing/api.py:695] Traceback (most recent call last):
E0709 21:30:16.481000 140636677933952 torch/distributed/elastic/multiprocessing/api.py:695]   File "/usr/local/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/api.py", line 656, in _poll
E0709 21:30:16.481000 140636677933952 torch/distributed/elastic/multiprocessing/api.py:695]     self._pc.join(-1)
E0709 21:30:16.481000 140636677933952 torch/distributed/elastic/multiprocessing/api.py:695]   File "/usr/local/lib/python3.11/site-packages/torch/multiprocessing/spawn.py", line 177, in join
E0709 21:30:16.481000 140636677933952 torch/distributed/elastic/multiprocessing/api.py:695]     raise ProcessExitedException(
E0709 21:30:16.481000 140636677933952 torch/distributed/elastic/multiprocessing/api.py:695] torch.multiprocessing.spawn.ProcessExitedException: process 0 terminated with exit code 1
Torch distributed launch config settings: {'min_nodes': 2, 'max_nodes': 2, 'node_rank': 1, 'nproc_per_node': 1, 'rdzv_backend': 'static', 'rdvz_endpoint_url': 'torch-ddp-0-e7f79f1f-09db-42fa-bfbb-a465847e2851.argo.svc.cluster.local', 'rdvz_endpoint_port': 29200, 'run_id': '1', 'role': '', 'max_restarts': 3, 'monitor_interval': 30.0, 'redirects': '3', 'tee': '3', 'log_dir': None, 'log_line_prefix_template': None}
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.11/multiprocessing/spawn.py", line 122, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/multiprocessing/spawn.py", line 131, in _main
    prepare(preparation_data)
  File "/usr/local/lib/python3.11/multiprocessing/spawn.py", line 246, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/usr/local/lib/python3.11/multiprocessing/spawn.py", line 297, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen runpy>", line 291, in run_path
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "/argo/staging/script", line 57, in <module>
    torch_distributed_function(n_iter,n_seconds_sleep,duration)
  File "/src/bettmensch-ai/sdk/bettmensch_ai/torch_utils.py", line 120, in wrapper
    elastic_launch(
  File "/usr/local/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 254, in launch_agent
    result = agent.run()
             ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/distributed/elastic/metrics/api.py", line 123, in wrapper
    result = f(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/distributed/elastic/agent/server/api.py", line 733, in run
    result = self._invoke_run(role)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/distributed/elastic/agent/server/api.py", line 870, in _invoke_run
    self._initialize_workers(self._worker_group)
  File "/usr/local/lib/python3.11/site-packages/torch/distributed/elastic/metrics/api.py", line 123, in wrapper
    result = f(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/distributed/elastic/agent/server/api.py", line 708, in _initialize_workers
    worker_ids = self._start_workers(worker_group)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/distributed/elastic/metrics/api.py", line 123, in wrapper
    result = f(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/distributed/elastic/agent/server/local_elastic_agent.py", line 279, in _start_workers
    self._pcontext = start_processes(
                     ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/__init__.py", line 231, in start_processes
    context.start()
  File "/usr/local/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/api.py", line 454, in start
    self._start()
  File "/usr/local/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/api.py", line 627, in _start
    self._pc = mp.start_processes(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/multiprocessing/spawn.py", line 228, in start_processes
    process.start()
  File "/usr/local/lib/python3.11/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/local/lib/python3.11/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/local/lib/python3.11/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/multiprocessing/spawn.py", line 164, in get_preparation_data
    _check_not_importing_main()
  File "/usr/local/lib/python3.11/multiprocessing/spawn.py", line 140, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

        To fix this issue, refer to the "Safe importing of main module"
        section in https://docs.python.org/3/library/multiprocessing.html
        
E0709 21:30:46.492000 140636677933952 torch/distributed/elastic/multiprocessing/api.py:695] failed (exitcode: 1) local_rank: 0 (pid: 17) of fn: torch_ddp (start_method: spawn)
E0709 21:30:46.492000 140636677933952 torch/distributed/elastic/multiprocessing/api.py:695] Traceback (most recent call last):
E0709 21:30:46.492000 140636677933952 torch/distributed/elastic/multiprocessing/api.py:695]   File "/usr/local/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/api.py", line 656, in _poll
E0709 21:30:46.492000 140636677933952 torch/distributed/elastic/multiprocessing/api.py:695]     self._pc.join(-1)
E0709 21:30:46.492000 140636677933952 torch/distributed/elastic/multiprocessing/api.py:695]   File "/usr/local/lib/python3.11/site-packages/torch/multiprocessing/spawn.py", line 177, in join
E0709 21:30:46.492000 140636677933952 torch/distributed/elastic/multiprocessing/api.py:695]     raise ProcessExitedException(
E0709 21:30:46.492000 140636677933952 torch/distributed/elastic/multiprocessing/api.py:695] torch.multiprocessing.spawn.ProcessExitedException: process 0 terminated with exit code 1
Torch distributed launch config settings: {'min_nodes': 2, 'max_nodes': 2, 'node_rank': 1, 'nproc_per_node': 1, 'rdzv_backend': 'static', 'rdvz_endpoint_url': 'torch-ddp-0-e7f79f1f-09db-42fa-bfbb-a465847e2851.argo.svc.cluster.local', 'rdvz_endpoint_port': 29200, 'run_id': '1', 'role': '', 'max_restarts': 3, 'monitor_interval': 30.0, 'redirects': '3', 'tee': '3', 'log_dir': None, 'log_line_prefix_template': None}
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.11/multiprocessing/spawn.py", line 122, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/multiprocessing/spawn.py", line 131, in _main
    prepare(preparation_data)
  File "/usr/local/lib/python3.11/multiprocessing/spawn.py", line 246, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/usr/local/lib/python3.11/multiprocessing/spawn.py", line 297, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen runpy>", line 291, in run_path
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "/argo/staging/script", line 57, in <module>
    torch_distributed_function(n_iter,n_seconds_sleep,duration)
  File "/src/bettmensch-ai/sdk/bettmensch_ai/torch_utils.py", line 120, in wrapper
    elastic_launch(
  File "/usr/local/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 254, in launch_agent
    result = agent.run()
             ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/distributed/elastic/metrics/api.py", line 123, in wrapper
    result = f(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/distributed/elastic/agent/server/api.py", line 733, in run
    result = self._invoke_run(role)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/distributed/elastic/agent/server/api.py", line 870, in _invoke_run
    self._initialize_workers(self._worker_group)
  File "/usr/local/lib/python3.11/site-packages/torch/distributed/elastic/metrics/api.py", line 123, in wrapper
    result = f(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/distributed/elastic/agent/server/api.py", line 708, in _initialize_workers
    worker_ids = self._start_workers(worker_group)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/distributed/elastic/metrics/api.py", line 123, in wrapper
    result = f(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/distributed/elastic/agent/server/local_elastic_agent.py", line 279, in _start_workers
    self._pcontext = start_processes(
                     ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/__init__.py", line 231, in start_processes
    context.start()
  File "/usr/local/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/api.py", line 454, in start
    self._start()
  File "/usr/local/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/api.py", line 627, in _start
    self._pc = mp.start_processes(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/multiprocessing/spawn.py", line 228, in start_processes
    process.start()
  File "/usr/local/lib/python3.11/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/local/lib/python3.11/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/local/lib/python3.11/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/multiprocessing/spawn.py", line 164, in get_preparation_data
    _check_not_importing_main()
  File "/usr/local/lib/python3.11/multiprocessing/spawn.py", line 140, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

        To fix this issue, refer to the "Safe importing of main module"
        section in https://docs.python.org/3/library/multiprocessing.html
        
E0709 21:31:16.499000 140636677933952 torch/distributed/elastic/multiprocessing/api.py:695] failed (exitcode: 1) local_rank: 0 (pid: 18) of fn: torch_ddp (start_method: spawn)
E0709 21:31:16.499000 140636677933952 torch/distributed/elastic/multiprocessing/api.py:695] Traceback (most recent call last):
E0709 21:31:16.499000 140636677933952 torch/distributed/elastic/multiprocessing/api.py:695]   File "/usr/local/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/api.py", line 656, in _poll
E0709 21:31:16.499000 140636677933952 torch/distributed/elastic/multiprocessing/api.py:695]     self._pc.join(-1)
E0709 21:31:16.499000 140636677933952 torch/distributed/elastic/multiprocessing/api.py:695]   File "/usr/local/lib/python3.11/site-packages/torch/multiprocessing/spawn.py", line 177, in join
E0709 21:31:16.499000 140636677933952 torch/distributed/elastic/multiprocessing/api.py:695]     raise ProcessExitedException(
E0709 21:31:16.499000 140636677933952 torch/distributed/elastic/multiprocessing/api.py:695] torch.multiprocessing.spawn.ProcessExitedException: process 0 terminated with exit code 1
Torch distributed launch config settings: {'min_nodes': 2, 'max_nodes': 2, 'node_rank': 1, 'nproc_per_node': 1, 'rdzv_backend': 'static', 'rdvz_endpoint_url': 'torch-ddp-0-e7f79f1f-09db-42fa-bfbb-a465847e2851.argo.svc.cluster.local', 'rdvz_endpoint_port': 29200, 'run_id': '1', 'role': '', 'max_restarts': 3, 'monitor_interval': 30.0, 'redirects': '3', 'tee': '3', 'log_dir': None, 'log_line_prefix_template': None}
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.11/multiprocessing/spawn.py", line 122, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/multiprocessing/spawn.py", line 131, in _main
    prepare(preparation_data)
  File "/usr/local/lib/python3.11/multiprocessing/spawn.py", line 246, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/usr/local/lib/python3.11/multiprocessing/spawn.py", line 297, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen runpy>", line 291, in run_path
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "/argo/staging/script", line 57, in <module>
    torch_distributed_function(n_iter,n_seconds_sleep,duration)
  File "/src/bettmensch-ai/sdk/bettmensch_ai/torch_utils.py", line 120, in wrapper
    elastic_launch(
  File "/usr/local/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 254, in launch_agent
    result = agent.run()
             ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/distributed/elastic/metrics/api.py", line 123, in wrapper
    result = f(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/distributed/elastic/agent/server/api.py", line 733, in run
    result = self._invoke_run(role)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/distributed/elastic/agent/server/api.py", line 870, in _invoke_run
    self._initialize_workers(self._worker_group)
  File "/usr/local/lib/python3.11/site-packages/torch/distributed/elastic/metrics/api.py", line 123, in wrapper
    result = f(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/distributed/elastic/agent/server/api.py", line 708, in _initialize_workers
    worker_ids = self._start_workers(worker_group)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/distributed/elastic/metrics/api.py", line 123, in wrapper
    result = f(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/distributed/elastic/agent/server/local_elastic_agent.py", line 279, in _start_workers
    self._pcontext = start_processes(
                     ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/__init__.py", line 231, in start_processes
    context.start()
  File "/usr/local/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/api.py", line 454, in start
    self._start()
  File "/usr/local/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/api.py", line 627, in _start
    self._pc = mp.start_processes(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/multiprocessing/spawn.py", line 228, in start_processes
    process.start()
  File "/usr/local/lib/python3.11/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/local/lib/python3.11/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/local/lib/python3.11/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/multiprocessing/spawn.py", line 164, in get_preparation_data
    _check_not_importing_main()
  File "/usr/local/lib/python3.11/multiprocessing/spawn.py", line 140, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

        To fix this issue, refer to the "Safe importing of main module"
        section in https://docs.python.org/3/library/multiprocessing.html
        
E0709 21:31:46.509000 140636677933952 torch/distributed/elastic/multiprocessing/api.py:695] failed (exitcode: 1) local_rank: 0 (pid: 19) of fn: torch_ddp (start_method: spawn)
E0709 21:31:46.509000 140636677933952 torch/distributed/elastic/multiprocessing/api.py:695] Traceback (most recent call last):
E0709 21:31:46.509000 140636677933952 torch/distributed/elastic/multiprocessing/api.py:695]   File "/usr/local/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/api.py", line 656, in _poll
E0709 21:31:46.509000 140636677933952 torch/distributed/elastic/multiprocessing/api.py:695]     self._pc.join(-1)
E0709 21:31:46.509000 140636677933952 torch/distributed/elastic/multiprocessing/api.py:695]   File "/usr/local/lib/python3.11/site-packages/torch/multiprocessing/spawn.py", line 177, in join
E0709 21:31:46.509000 140636677933952 torch/distributed/elastic/multiprocessing/api.py:695]     raise ProcessExitedException(
E0709 21:31:46.509000 140636677933952 torch/distributed/elastic/multiprocessing/api.py:695] torch.multiprocessing.spawn.ProcessExitedException: process 0 terminated with exit code 1
Traceback (most recent call last):
  File "/argo/staging/script", line 57, in <module>
    torch_distributed_function(n_iter,n_seconds_sleep,duration)
  File "/src/bettmensch-ai/sdk/bettmensch_ai/torch_utils.py", line 120, in wrapper
    elastic_launch(
  File "/usr/local/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 263, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
torch_ddp FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-07-09_21:31:46
  host      : pipeline-test-torch-pipeline-dggrw-flow-5c7p7-torch-ddp-1-14783
  rank      : 1 (local_rank: 0)
  exitcode  : 1 (pid: 19)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
time="2024-07-09T21:31:49.306Z" level=info msg="sub-process exited" argo=true error="<nil>"
time="2024-07-09T21:31:49.319Z" level=error msg="cannot save parameter duration" argo=true error="open duration: no such file or directory"
Error: exit status 1
